Repository CSEdgeOfficial/learn.csedge.courses, pull requests merged in 2024-05, with the labels that each got.

#37 Added home page link to the logo text in all html files
  index.html
  posts/azure/How-to-Create-an-Azure-Account.html
  posts/github/How-to-Apply-for-GitHub-Student-Developer-Pack.html
  posts/github/How-to-Make-Pull-Requests-on-GitHub.html
  posts/github/how-to-create-github-account.html
  posts/java/how-to-install-jdk.html
  posts/linkedin/creating-professional-linkedin-account.html
  posts/technology/how-to-create-JSON-Server.html
Labels: good first issue, GSSoC'24, Level-1

#51 Added logo in the Blog page
  css/styles.css
  index.html
  posts/azure/How-to-Create-an-Azure-Account.html
  posts/github/How-to-Apply-for-GitHub-Student-Developer-Pack.html
  posts/github/How-to-Make-Pull-Requests-on-GitHub.html
  posts/github/how-to-create-github-account.html
  posts/java/how-to-install-jdk.html
  posts/linkedin/creating-professional-linkedin-account.html
  posts/technology/how-to-create-JSON-Server.html
Labels: GSSoC'24, Level-1

#57 Blog title position is fixed
  posts/azure/How-to-Create-an-Azure-Account.html
  posts/github/How-to-Apply-for-GitHub-Student-Developer-Pack.html
  posts/github/How-to-Make-Pull-Requests-on-GitHub.html
  posts/github/how-to-create-github-account.html
  posts/linkedin/creating-professional-linkedin-account.html
  posts/styles.css
Labels: good first issue, GSSoC'24, Level-1

#71 Fixing aligment of arrowKey
  csedge.courses/navbar.css
  navbar.css
Labels: good first issue, GSSoC'24, Level-1

#81 Update home.html
  home.html
Labels: documentation, good first issue, GSSoC'24, Level-1

#106 Free content section #63
  csedge.courses/Images/c++.svg
  csedge.courses/Images/css.svg
  csedge.courses/Images/node.svg
  csedge.courses/Images/react.svg
  csedge.courses/Resources.html
Labels: enhancement, GSSoC'24, Level-1

#153 feat: automate greetings using github bot
  .github/workflows/greetings.yml
Labels: GSSoC'24, Level-1

#159 Solved issue #142- Adding suitable icons .
  home.html
  navbar.css
Labels: GSSoC'24, Level1

#148 Issue Number :#142 Added suitable icons
  index.html
Labels: good first issue, GSSoC'24, Level1

#101 fixed navbar at the top with some hover effects
  home.css
  navbar.css
Labels: good first issue, GSSoC'24, Level1, UI

#180 Videos section
  csedge.courses/Resources.html
Labels: good first issue, GSSoC'24, Level1

#187 Add dynamic current year to footer
  csedge.courses/Internships/Full-Stack-Development.html
  csedge.courses/Internships/Java.html
  csedge.courses/Internships/Web-Development.html
  csedge.courses/Internships/python.html
  csedge.courses/Resources.html
  csedge.courses/about.html
  csedge.courses/index.html
  csedge.courses/internship.html
  csedge.courses/verify-id.html
  index.html
Labels: enhancement, GSSoC'24, Level1

#185 improve the ui of navbar
  home.css
  home.html
  index.html
  navbar.css
Labels: GSSoC'24, Level1, UI

#199 Fixed issue #193
  home.html
Labels: documentation, GSSoC'24, Level1

#196 feat: scrolltotopbutton added
  ScrollToTop.js
  button.css
  csedge.courses/Resources.html
  csedge.courses/ScrollToTop.js
  csedge.courses/index.css
  csedge.courses/up-arrow2.png
  index.html
  up-arrow2.png
Labels: enhancement, GSSoC'24, Level2

#202 changes Navbar icons and fixed the navbar at top
  csedge.courses/index.html
  csedge.courses/navbar.css
  css/styles.css
  home.html
  index.html
  navbar.css
Labels: good first issue, GSSoC'24, Level1, UI

#214 Added Privacy Policy page
  csedge.courses/privacypolicy.css
  csedge.courses/privacypolicy.html
  index.html
Labels: documentation, GSSoC'24, Level1

#215 Home page made responsive, Improve Navbar
  home.css
  home.html
Labels: GSSoC'24, Level2, UI

#230 Removed unecessary spaces
  css/styles.css
  index.html
Labels: GSSoC'24, Level1, UI

#233 Create autocomment-pr-raise.yml
  .github/workflows/autocomment-pr-raise.yml
Labels: GSSoC'24, Level1

#232 Create autocomment-issue.yml
  .github/workflows/autocomment-issue.yml
Labels: GSSoC'24, Level1

#248 Grammar, Punctuation and case sensitive errors fixed
  .idea/.gitignore
  .idea/learn.csedge.courses.iml
  .idea/modules.xml
  .idea/vcs.xml
  home.html
Labels: documentation, good first issue, GSSoC'24, Level1

#277 Added margin to heading
  css/styles.css
  index.html
Labels: good first issue, GSSoC'24, Level1, UI

#88 Fix the Alignment of Text in About Section
  csedge.courses/about.html
  csedge.courses/index.css
Labels: GSSoC'24, Level1

#298 [Techical Writing] Detailed article on how to create REST API
  index.html
  posts/images/Final-output.png
  posts/images/api-return.png
  posts/images/mongo-db-connection.png
  posts/images/mongodb-atlas-connection.png
  posts/images/mongodb-connection.png
  posts/images/project-details.png
  posts/images/render-repo-info.png
  posts/images/render-service.png
  posts/technology/How-to-build-rest-api-using-node-and-mongo-db.html
Labels: GSSoC'24, Level3

#308 Removed Conflict & made changes to footer
  css/styles.css
  index.html
Labels: gssoc24, level1, UI

#313 Make changes in the Next and Previous Section
  index.html
Labels: good first issue, gssoc24, level1

#273 Add Dark Mode
  home.css
  home.html
  navbar.css
Labels: gssoc24, level3, UI

#97 post progress bar
  posts/script.js
  posts/styles.css
  posts/technology/how-to-create-JSON-Server.html
Labels: gssoc24, level2

#328 contact,home link fixed
  home.html
Labels: gssoc24, level1

#336 Make Navbar properly aligned in DESKTOP mode.
  index.html
Labels: bug, gssoc24, level2, UI

#338 Added parallax effect on cards
  home.html
  vanilla-tilt.js
Labels: gssoc, level2, UI
