Repository CSEdgeOfficial/learn.csedge.courses, pull requests merged in 2024-07, with the labels that each got.

#528 Added How to create user info based Resume maker
  Web Development/How-To-Create-user-info-based-Resume-Maker/index.html
  posts/images/How-to-create-user-info-based-Resume-maker.png
Labels: gssoc, level1

#501 Image Classifivation with TensorFLow/Keras
  posts/Image Classification/ImageClassificationWithTensorFLow.html
  posts/images/Image_Classification.png
Labels: gssoc, level1

#535 Added How-To-Create-AR-Website-With-3D-Object-Placement
  Web Development/How-To-Create-AR-Website-With-3D-Object-Placement/index.html
  posts/images/How-To-Create-AR-Website-With-3D-Object-Placement.png
Labels: gssoc, level1

#543 Navbar New hovering affect added
  index.html
Labels: gssoc, level1, UI

#551 New Home Created
  FRONTEND/csedge/.gitignore
  FRONTEND/csedge/README.md
  FRONTEND/csedge/package-lock.json
  FRONTEND/csedge/package.json
  FRONTEND/csedge/postcss.config.js
  FRONTEND/csedge/public/favicon.ico
  FRONTEND/csedge/public/index.html
  FRONTEND/csedge/public/logo192.png
  FRONTEND/csedge/public/logo512.png
  FRONTEND/csedge/public/manifest.json
  FRONTEND/csedge/public/robots.txt
  FRONTEND/csedge/src/App.css
  FRONTEND/csedge/src/App.js
  FRONTEND/csedge/src/App.test.js
  FRONTEND/csedge/src/Pages/Contact.jsx
  FRONTEND/csedge/src/Pages/Home.jsx
  FRONTEND/csedge/src/components/About.jsx
  FRONTEND/csedge/src/components/Footer.jsx
  FRONTEND/csedge/src/components/Hero.jsx
  FRONTEND/csedge/src/components/Navbar.jsx
  FRONTEND/csedge/src/components/Pricing.jsx
  FRONTEND/csedge/src/components/Testimonial.jsx
  FRONTEND/csedge/src/index.css
  FRONTEND/csedge/src/index.js
  FRONTEND/csedge/src/logo.svg
  FRONTEND/csedge/src/reportWebVitals.js
  FRONTEND/csedge/src/setupTests.js
  FRONTEND/csedge/tailwind.config.js
  index.html
Labels: gssoc, level3

#556 bottom to top functionality added
  index.html
Labels: gssoc, level1

#576 Added How Article How to Create ECommerce Webpage
  Web Development/How-To-Create-a-Ecommerce-Webpage/index.html
  posts/images/How-To-Create-a-Ecommerce-Webpage.png
Labels: gssoc, level1
