Repository CSEdgeOfficial/learn.csedge.courses, pull requests merged in 2024-06, with the labels that each got.

#375 CSS file for form section.
  form.css
  posts/github/Github-Pages
Labels: gssoc, level1

#383 Fixed navbar navlinks and positioning of hamburger menu
  home.html
  navbar.css
Labels: gssoc, level1, UI

#389 Fixes #343
  chatbox.css
  chatbox.js
  home.css
  home.html
  navbar.css
Labels: gssoc, level2

#393 Added Hover Effects to Contact Links and Implemented Contact Form in Contact Section
  ScrollToTop.js
  home.css
  home.html
  new/web-developer.251x256.png
Labels: gssoc, level2

#405 Changed Footer
  css/main.css
  home.css
  home.html
Labels: gssoc, level2

#436 [Feature] Navbar sections buttons added hover effect.
  index.html
Labels: gssoc, level1

#441 after click on hamburger dialog open but that icon needs to replace with cross icon instead of hamburger #435
  css/styles.css
  index.html
Labels: gssoc, level1

#454 Added Blog on Power BI
  index.html
  posts/powerBI/powerBI.html
  posts/powerBI/powerBI.png
  powerBI.png
Labels: gssoc, level1

#449 Solved the pagination issue
  home.css
  home.html
  index.html
  posts/docker/Getting-Started-with-Docker.html
  posts/master-docker.html
  posts/master-github.html
Labels: gssoc, level2

#462 Technical Content of chatbot with NLTK.
  posts/ChatBot with NLTK/Building-chatBot-with-NLTK.html
  posts/images/Beautiful Soup for web scraping.png
  posts/images/Monitors.png
  posts/images/WebScrapingImage.png
Labels: gssoc, level1

#464 Added Hover Effect in Footer Links
  csedge.courses/index.css
Labels: gssoc, level1

#455 Added A line for copyright section
  index.html
Labels: gssoc, level1

#473 Added subscribe to newsletter
  index.html
Labels: gssoc, level1

#475 Added Hover Effect for the subscribe to newsletter button
  index.html
Labels: gssoc, level1

#485 Added how to host websites using netlify
  css/styles.css
  index.html
  posts/images/How-to-host-using-netlify.jpg
  posts/technology/how-to-host-websites-using-netlify.html
Labels: gssoc, level1

#118 added a codesnippet in an article
  posts/java/hello-world-in-java.css
  posts/java/hello-world-in-java.html
  posts/javascript/javascript-basics.css
  posts/javascript/javascript-basics.html
Labels: gssoc, level2

#509 dynamically state and fetching added
  data.json
  home.html
  index.html
Labels: enhancement, gssoc, level3

#516 Added How To host using Vercel
  posts/images/How-to-Host-Using-Vercel.png
  posts/technology/How-to-Host-Using-vercel.html
Labels: gssoc, level1

#519 Added How To Create a Parallax Website
  Web Development/How-To-Create-Parallax-Website/index.html
  Web Development/main.css
  Web Development/styles.css
Labels: gssoc, level1
